# Generated by Django 6.0 on 2026-01-19 10:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskuser',
            name='country',
            field=django_countries.fields.CountryField(default='BG', max_length=2),
            preserve_default=False,
        ),
    ]
