# Generated by Django 6.0 on 2026-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pet owner", "Pet owner"),
                    ("volunteer", "Volunteer"),
                    ("shelter", "Shelter"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
