# Generated by Django 6.0 on 2026-02-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no type", "Do not specify"),
                    ("pet owner", "Pet owner"),
                    ("volunteer", "Volunteer"),
                    ("shelter", "Shelter"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
