# Generated by Django 6.0 on 2025-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=70)),
                ('found', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
