# Generated by Django 6.0 on 2026-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petlocation',
            old_name='date_seen',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='petlocation',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
