# Generated by Django 6.0 on 2026-03-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petlocation",
            name="street_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
