# Generated by Django 6.0 on 2026-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_petlocation_street_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="animal_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
