# Generated by Django 6.0 on 2026-01-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_petlocation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlocation',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='posts.post'),
            preserve_default=False,
        ),
    ]
