# Generated by Django 6.0 on 2026-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_petlocation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlocation',
            name='posts',
            field=models.ManyToManyField(related_name='locations', to='posts.post'),
        ),
    ]
