# Generated by Django 6.0 on 2026-02-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_savedpost_post_saved_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petlocation",
            options={"ordering": ["-is_valid"]},
        ),
    ]
