# Generated by Django 6.0 on 2026-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_petlocation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-posted_on"]},
        ),
    ]
