# Generated by Django 6.0 on 2026-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("location", "Location"), ("comment", "Comment")],
                max_length=20,
            ),
        ),
    ]
