# Generated by Django 6.0 on 2026-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="post_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
